Acme\ShopBundle\Entity\Client:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
