acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_shops:
    resource: "@AcmeShopBundle/Resources/config/routing.yml"
    prefix:   /

_assetic:
    resource: .
    type:     assetic