#_welcome:
#    pattern:  /
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }

#_shop_secured:
#    resource: "@AcmeShopBundle/Controller/SecuredController.php"
#    type:     annotation

#_shop:
#    resource: "@AcmeShopBundle/Controller/DefaultController.php"
#    type:     annotation
#    prefix:   /shop
    
#_demo2:
#    resource: "@AcmeDemoBundle/Controller/Demo2Controller.php"
#    type:     annotation
#    prefix:   /demo2



acme_shop_search_shops:
    pattern:  /calc/searchShops
    defaults: { _controller: AcmeShopBundle:Calculator:calculateShopsByCoordinates }
#    prefix:   /shop

acme_shop_homepage:
    pattern:  /calc
    defaults: { _controller: AcmeShopBundle:Calculator:index }
    
#acme_shop_insert_client:
#    pattern:  /shop/insertClient
#    defaults: { _controller: AcmeShopBundle:Shop:insertClient }
    
#load_client_by_id:
#    pattern: /shop/loadClientById/{id}
#    defaults: { _controller: AcmeShopBundle:Shop:loadClientById }
#    requirements:
#        page: \d+
        
#client_crud:
#pattern: /client/{action}
#    defaults: { _controller: AcmeShopBundle:Client:index }

AcmeShopBundle_client_crud:
        resource: "@AcmeShopBundle/Resources/config/routing/client.yml"
        prefix:   /client_crud
        
AcmeShopBundle_shop_crud:
        resource: "@AcmeShopBundle/Resources/config/routing/shop.yml"
        prefix:   /shop_crud


