parameters:
#    acme_shop.example.class: Acme\ShopBundle\Example

services:
#    acme_shop.example:
#        class: %acme_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#services:
#    acme_shop.client:
#        class: Acme\ShopBundle\Service\ClientService
#        arguments: [@doctrine.orm.default_entity_manager]
        
services:
    acme_shop.client:
        class: Acme\ShopBundle\Controller\ClientController
        calls:
            - [setContainer, ["@service_container"]]
#        arguments: [@doctrine.orm.default_entity_manager]
