parameters:
#    acme_shop.example.class: Acme\ShopBundle\Example

services:
#    acme_shop.example:
#        class: %acme_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
