# src/Acme/ShopBundle/Resources/config/validation.yml
Acme\ShopBundle\Controller\ShopController:
    properties:
        longitude, latitude:
            - NotBlank: ~
            - Range: ~
        radius:
            - NotBlank: ~
            - Range: ~
            - GreaterThan: 0