parameters:
#    acme_shops.example.class: Acme\ShopsBundle\Example

services:
#    acme_shops.example:
#        class: %acme_shops.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
