Acme\DemoBundle\Entity\Musician:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '40'
        email:
            type: string
            length: '150'
        age:
            type: string
            length: '3'
    lifecycleCallbacks: {  }
